name: playground
description: "Playground for LLMs Chat"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <=4.0.0'

dependency_overrides:
  intl: any

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  web: ^1.1.1
  go_router: ^16.0.0

  intl: ^0.19.0
  flutter_native_splash: ^2.4.2

  # Firebase Crashlytics
  firebase_crashlytics: ^5.0.0

  # Animation Lottie
  lottie: ^3.1.3

  # Flutter Toast
  toastification: ^3.0.3

  # load images from internet
  image: ^4.3.0
  cached_network_image: ^3.4.1

  # play audio waveform
  audio_waveforms: ^1.1.1
  audioplayers: ^6.4.0

  # web record
  record: ^6.0.0

  # view Photo
  photo_view: ^0.15.0

  # get vector file as image
  flutter_svg: ^2.0.11

  # get readmore button package
  readmore: ^3.0.0

  # Markdown Text
  markdown: ^7.3.0
  flutter_highlight: ^0.7.0
  flutter_math_fork: 0.7.3

  # ListView load more
  pull_to_refresh: ^2.0.0

  # state management package
  provider: ^6.0.5

  # Firebase Authentication
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0

  # Flutter Secure Storage
  flutter_secure_storage: ^9.0.0

  # Loading Screen
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2

  # Firebase Cloud Firestore
  cloud_firestore: ^6.0.0

  # Firebase Storage
  firebase_storage: ^13.0.0

  # HTTP request
  http: ^1.2.2

  # Url Launcher
  url_launcher: ^6.1.5

  # Permission for Camera, Photo, Phone, Microphone, and Notification
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/icons/
    - assets/images/

  fonts:
    - family: CustomOutlinedIcons
      fonts:
        - asset: fonts/Custom-Outlined-Icons.ttf
    - family: CustomFilledIcons
      fonts:
        - asset: fonts/Custom-Filled-Icons.ttf

    # Font Styles: Khmer & English
    - family: Kantumruy
      fonts:
        - asset: fonts/Kantumruy.ttf
    - family: Saira
      fonts:
        - asset: fonts/Saira.ttf
    - family: Tomorrow
      fonts:
        - asset: fonts/Tomorrow.ttf

flutter_native_splash:
  color: "#FF9988"
  image: assets/images/splash.png
  fullscreen: true
  android: true
  android_12:
    color: "#FF9988"
    image: assets/images/splash.png
    fullscreen: true

  ios: true
  web: false
